install:
- wget https://github.com/gohugoio/hugo/releases/download/v0.58.3/hugo_0.58.3_Windows-64bit.zip
- sudo dpkg -i hugo*.zip
- hugo version
before_script
- rm -rf public
script:
- hugo
branches:
  only:
  - master
  